### ISSUE TITLE
ogp_buildでエラーが発生する

### ISSUE THREAD

**Issue by katsuyoshi** [code4akita/covid19-akita#43]
## masterにmergeした後にogp_buildが起動されるがエラーが発生している

[ogb_build](https://github.com/code4akita/covid19-akita/blob/development/.github/workflows/ogp_builder.yml)

- スクリーンショットの作成でエラーになっていたが、covid19-akitaで使用いているものに制限しここはパスする様になった。 e504cb2
- 次のアップロードでエラーが出ている。

  ```
  Run ad-m/github-push-action@master
    with:
      github_token: ***
      directory: .
  Push to branch development
  To https://github.com/code4akita/covid19-akita.git
   ! [rejected]        HEAD -> development (fetch first)
  error: failed to push some refs to 'https://github.com/code4akita/covid19-akita.git'
  hint: Updates were rejected because the remote contains work that you do
  hint: not have locally. This is usually caused by another repository pushing
  hint: to the same ref. You may want to first integrate the remote changes
  hint: (e.g., 'git pull ...') before pushing again.
  hint: See the 'Note about fast-forwards' in 'git push --help' for details.
  Error: Invalid exit code: 1
      at ChildProcess.<anonymous> (/home/runner/work/_actions/ad-m/github-push-action/master/start.js:29:21)
      at ChildProcess.emit (events.js:210:5)
      at maybeClose (internal/child_process.js:1021:16)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5) {
    code: 1
  }
  Error: Invalid exit code: 1
      at ChildProcess.<anonymous> (/home/runner/work/_actions/ad-m/github-push-action/master/start.js:29:21)
      at ChildProcess.emit (events.js:210:5)
      at maybeClose (internal/child_process.js:1021:16)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
  Post Run actions/checkout@v2
  ```

**Comment by katsuyoshi** [comment]
一旦停止しました。

**Comment by katsuyoshi** [comment]
ogp_buildしなくても問題なさそうなので一旦クローズします。
